function circleArea(r){return Math.PI*r*r}
function circleCircumference(r){return 2*Math.PI*r}
function rectangleArea(w,h){return w*h}
function rectanglePerimeter(w,h){return 2*(w+h)}
function triangleArea(b,h){return .5*b*h}
function sphereVolume(r){return 4/3*Math.PI*r**3}
function sphereSurfaceArea(r){return 4*Math.PI*r*r}
function cylinderVolume(r,h){return Math.PI*r*r*h}
function coneVolume(r,h){return Math.PI*r*r*h/3}
function degreesToRadians(d){return d*Math.PI/180}
function pythagorean(a,b){return Math.sqrt(a*a+b*b)}
